# Generated by Django 6.0.7 on 2026-08-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_category_rename_in_stock_product_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
